# This file is placed in the Public Domain.


"event handler"


class Handler:

    def callback(self, evt) -> None: ...
    def loop(self) -> None: ...
    def poll(self): ...
    def put(self, evt) -> None: ...
    def register(self, typ, cbs) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def wait(self) -> None: ...
