# This file is placed in the Public Domain.


"a clean namespace"


class Object:

    def __contains__(self, key: str): ...
    def __iter__(self): ...
    def __len__(self): ...
    def __str__(self): ...


def construct(obj: Object, *args, **kwargs): ...
def fqn(obj: Object): ...
def items(obj: Object): ...
def keys(obj: Object): ...
def update(obj: Object, data: dict): ...
def values(obj: Object): ...


def __dir__():
    return (
        'Object',
        'construct',
        'fqn',
        'items',
        'keys',
        'update',
        'values'
    )
