# This file is placed in the Public Domain.


[build-system]
requires = ["setuptools>=61.2", "wheel"]
build-backend = "setuptools.build_meta"


[project]
version = "500"
name = "nixt"
authors = [
    {name = "Nixt Niet", email = "nixtniet@proton.me" },
]
description = "write your own commands"
readme = "README.rst"
license = "Unlicense"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3",
    "Topic :: Utilities"
]

[project.scripts]
"nixt" = "nixt.runtime:main"


[project.urls]
"home" = "https://github.com/nixtniet/nixt"
"bugs" = "https://github.com/nixtniet/nixt/issues"
"source" = "https://github.com/nixtniet/nixt"


[tool.setuptools]
packages = [
    'nixt',
]


[tool.pylint."messages control"]
disable = ["C0103,C0115,C0116,C0301,C0413,C0415,R0903,R0904,R0912,R0913,R0917,W0212,W0718,E0401,E0402"]


[tool.ruff.lint]
ignore = ["I001", "SIM905", "UP031", "UP041", "UP024", "DTZ005"]
