# This file is placed in the Public Domain.


"list of clients"


from typing import Any


class Fleet:

    clients = {}

    def add(clt) -> None: ...
    def all() -> list[Any]: ...
    def announce(txt) -> None: ...
    def display(evt) -> None: ...
    def first() -> None: ...
    def get(orig) -> None: ...
    def say(orig, channel, txt) -> None: ...
    def wait() -> None: ...
