# This file is placed in the Public Domain.


class Client:

    def __init__(self): ...
    def announce(self, txt: str) -> None: ...
    def raw(self, txt: str) -> None: ...
    def say(self, channel: str, txt: str) -> None: ...
