# This file is placed in the Public Domain.


from .object import Object


class Error(Exception): ...


class Cache:

    objs = {}

    @staticmethod
    def add(path: str, obj: Object): ...

    @staticmethod
    def get(path: str) -> Object: ...

    @staticmethod
    def typed(matcher: str) -> list[Object]: ...


def cdir(path: str) -> None: ...
def getpath(obj: Object) -> str: ...
def ident(obj: Object) -> str: ...
def read(obj: Object, path: str) -> None: ...
def write(obj: Object, path: str = ""): ...
