# This file is placed in the Public Domain.


from typing import Iterator


from .object import Object


def fns(clz: str) -> Iterator[str]: ...
def fntime(daystr: str) -> float: ...
def find(clz: str, selector: dict={}, deleted: bool=False, matching: bool=False) -> list[tuple[str, Object]]: ...
def isdeleted(obj: Object) -> bool: ...
def last(obj: Object, selector: dict={}) -> Object: ...
def search(obj: Object, selector: dict, matching: dict={}) -> bool: ...
