# This file is placed in the Public Domain.


class Workdir:

    name: str
    wdr: str


def long(name: str) -> str: ...
def moddir() -> str: ...
def pidname(name) -> str: ...
def skel() -> None: ...
def setwd(pth) -> None: ...
def store(pth: str=""): ...
def strip(pth: str, nmr: int=2): ...
def types() -> list[str]: ...
def wdr(pth: str) -> None: ...
